name: Check and generete Helm chart
on:
  push:
    paths:
      - "charts/**"
      - ".github/workflows/helm.yml"
  pull_request:
    paths:
      - "charts/**"
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch'
        required: true
        default: 'main'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Helm setup
        uses: azure/setup-helm@v4
        with:
          version: 'latest'
      - run: helm lint charts/PodInspector

  template:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-helm@v4
        with:
          version: 'latest'
      - run: helm template charts/PodInspector --values charts/PodInspector/values.yaml

  package:
    runs-on: ubuntu-latest
    needs: [lint, template]
    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-helm@v4
        with:
          version: 'latest'
      - run: helm package charts/PodInspector --destination charts/packages
      - uses: actions/upload-artifact@v4
        with:
          name: helm-packages
          path: charts/packages*
#  release:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/download-artifact@v4
#        with:
#          name: helm-packages
#          path: charts/packages
#      - name: Create GitHub Release with Helm package
#        uses: softprops/action-gh-release@v2
#        with:
#          files: charts/packages/*
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}