name: Check and build Python package

on:
  push:
    paths:
      - "app/**"
      - ".github/workflows/python.yml"
  pull_request:
    paths:
      - "app/**"
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch'
        required: true
        default: 'main'

jobs:
  lint-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.14]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.pythons-version }}
          cache: pip
      - run: pip install -r requirements.txt
      - run: pip install black flake8
      - run: black --check app/
      - run: flake8 app/ --max-line-length 120

  build:
    runs-on: ubuntu-latest
    needs: lint-test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.14
      - run: pip install build
      - run: python -m build app
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: app/dist/*
#  release:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/download-artifact@v4
#        with:
#          name: dist
#          path: app/dist/*
#      - name: Create GitHub Release with Helm package
#        uses: softprops/action-gh-release@v2
#        with:
#          files: app/dist/*
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}